package Core.extensions

import Core.interfaces.DBEntity
import Extensions.isAutoGeneratedMetaData
import Extensions.isIgnore
import java.sql.ResultSet
import kotlin.reflect.KMutableProperty
import kotlin.reflect.full.createInstance
import kotlin.reflect.full.memberProperties

/**
 * Created by Sanf0rd on 16/07/17.
 */
fun Class<DBEntity>.listWith(resultSet: ResultSet?): List<DBEntity> {

}